#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "motion_functions.h"

#define LIGHT_SENSOR_BLACK 37
#define LIGHT_SENSOR_WHITE 53

#define PIVOT_SPEED 15

task main()
{
	while(true) {
		int sensor_reading = SensorValue[lightSensor];
 		if (sensor_reading < LIGHT_SENSOR_BLACK) {
			pivot_left(PIVOT_SPEED);
		}
		else if (sensor_reading > LIGHT_SENSOR_WHITE) {
			pivot_right(PIVOT_SPEED);
		}
		else { // proportional control
			// normalize sensor reading to a value between 0.0 and 1.0, where 0.0 is black and 1.0 is white
			float normalized_reading = (float)(sensor_reading - LIGHT_SENSOR_BLACK) / (float)(LIGHT_SENSOR_WHITE - LIGHT_SENSOR_BLACK);
			motor[motorB] = 100;
			motor[motorC] = 100;
		}
	}
}
