#pragma config(Sensor, S2,     left_light_sensor, sensorLightActive)
#pragma config(Sensor, S3,     right_light_sensor, sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "motion_functions.h"
#include "math_functions.h"

#define LIGHT_SENSOR_BLACK 38 // originally 37
#define LIGHT_SENSOR_WHITE 62 // originally 53

#define PIVOT_SPEED 25
#define MAX_SPEED 25
#define MIN_SPEED 30

#define DEAD_ZONE_OFFSET 0.1

// attempt at two sensors. didn't really work

// uncomment this line to make cool noises
//#define MELODIES

int LIGHT_SENSOR_MIDDLE = (LIGHT_SENSOR_WHITE + LIGHT_SENSOR_BLACK) / 2;

task main()
{
	while(true) {
		int left_reading = SensorValue[left_light_sensor];
 		int right_reading = SensorValue[right_light_sensor];
 		if (left_reading < LIGHT_SENSOR_MIDDLE && right_reading < LIGHT_SENSOR_MIDDLE) {
			motor[motorB] = -10;
			motor[motorC] = -10;
			playTone(900, 1);
		}
		else if (right_reading < LIGHT_SENSOR_MIDDLE) {
			pivot_left(PIVOT_SPEED);
		}
		else if (left_reading < LIGHT_SENSOR_MIDDLE) {
			pivot_right(PIVOT_SPEED);
		}
		else {
			motor[motorB] = MAX_SPEED;
			motor[motorC] = MAX_SPEED;
		}
		float normalized_speed = (motor[motorB] + 100.0) / 200.0; // 0.0 to 1.0
		int freq = normalized_speed * 500 + 700;
#ifdef MELODIES
		playTone(freq,1);
#endif
	}
}
